apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: beegfs-csi-driver-operator-controller-manager-metrics-service
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
