//go:build !ignore_autogenerated

/*
Copyright 2021 NetApp, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeegfsConfig) DeepCopyInto(out *BeegfsConfig) {
	*out = *in
	if in.ConnInterfaces != nil {
		in, out := &in.ConnInterfaces, &out.ConnInterfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnNetFilter != nil {
		in, out := &in.ConnNetFilter, &out.ConnNetFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnTcpOnlyFilter != nil {
		in, out := &in.ConnTcpOnlyFilter, &out.ConnTcpOnlyFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BeegfsClientConf != nil {
		in, out := &in.BeegfsClientConf, &out.BeegfsClientConf
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConnRDMAInterfaces != nil {
		in, out := &in.ConnRDMAInterfaces, &out.ConnRDMAInterfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeegfsConfig.
func (in *BeegfsConfig) DeepCopy() *BeegfsConfig {
	if in == nil {
		return nil
	}
	out := new(BeegfsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeegfsDriver) DeepCopyInto(out *BeegfsDriver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeegfsDriver.
func (in *BeegfsDriver) DeepCopy() *BeegfsDriver {
	if in == nil {
		return nil
	}
	out := new(BeegfsDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeegfsDriver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeegfsDriverList) DeepCopyInto(out *BeegfsDriverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BeegfsDriver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeegfsDriverList.
func (in *BeegfsDriverList) DeepCopy() *BeegfsDriverList {
	if in == nil {
		return nil
	}
	out := new(BeegfsDriverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeegfsDriverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeegfsDriverSpec) DeepCopyInto(out *BeegfsDriverSpec) {
	*out = *in
	out.ContainerImageOverrides = in.ContainerImageOverrides
	in.ContainerResourceOverrides.DeepCopyInto(&out.ContainerResourceOverrides)
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(int)
		**out = **in
	}
	in.NodeAffinityControllerService.DeepCopyInto(&out.NodeAffinityControllerService)
	in.NodeAffinityNodeService.DeepCopyInto(&out.NodeAffinityNodeService)
	in.PluginConfigFromFile.DeepCopyInto(&out.PluginConfigFromFile)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeegfsDriverSpec.
func (in *BeegfsDriverSpec) DeepCopy() *BeegfsDriverSpec {
	if in == nil {
		return nil
	}
	out := new(BeegfsDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeegfsDriverStatus) DeepCopyInto(out *BeegfsDriverStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeegfsDriverStatus.
func (in *BeegfsDriverStatus) DeepCopy() *BeegfsDriverStatus {
	if in == nil {
		return nil
	}
	out := new(BeegfsDriverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnAuthConfig) DeepCopyInto(out *ConnAuthConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnAuthConfig.
func (in *ConnAuthConfig) DeepCopy() *ConnAuthConfig {
	if in == nil {
		return nil
	}
	out := new(ConnAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageOverride) DeepCopyInto(out *ContainerImageOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageOverride.
func (in *ContainerImageOverride) DeepCopy() *ContainerImageOverride {
	if in == nil {
		return nil
	}
	out := new(ContainerImageOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageOverrides) DeepCopyInto(out *ContainerImageOverrides) {
	*out = *in
	out.BeegfsCsiDriver = in.BeegfsCsiDriver
	out.CsiNodeDriverRegistrar = in.CsiNodeDriverRegistrar
	out.CsiProvisioner = in.CsiProvisioner
	out.CsiResizer = in.CsiResizer
	out.LivenessProbe = in.LivenessProbe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageOverrides.
func (in *ContainerImageOverrides) DeepCopy() *ContainerImageOverrides {
	if in == nil {
		return nil
	}
	out := new(ContainerImageOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceOverrides) DeepCopyInto(out *ContainerResourceOverrides) {
	*out = *in
	in.ControllerBeegfsResources.DeepCopyInto(&out.ControllerBeegfsResources)
	in.ControllerCsiProvisionerResources.DeepCopyInto(&out.ControllerCsiProvisionerResources)
	in.NodeBeegfsResources.DeepCopyInto(&out.NodeBeegfsResources)
	in.NodeDriverRegistrarResources.DeepCopyInto(&out.NodeDriverRegistrarResources)
	in.NodeLivenessProbeResources.DeepCopyInto(&out.NodeLivenessProbeResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceOverrides.
func (in *ContainerResourceOverrides) DeepCopy() *ContainerResourceOverrides {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemSpecificConfig) DeepCopyInto(out *FileSystemSpecificConfig) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemSpecificConfig.
func (in *FileSystemSpecificConfig) DeepCopy() *FileSystemSpecificConfig {
	if in == nil {
		return nil
	}
	out := new(FileSystemSpecificConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSpecificConfig) DeepCopyInto(out *NodeSpecificConfig) {
	*out = *in
	if in.NodeList != nil {
		in, out := &in.NodeList, &out.NodeList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.DefaultConfig.DeepCopyInto(&out.DefaultConfig)
	if in.FileSystemSpecificConfigs != nil {
		in, out := &in.FileSystemSpecificConfigs, &out.FileSystemSpecificConfigs
		*out = make([]FileSystemSpecificConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSpecificConfig.
func (in *NodeSpecificConfig) DeepCopy() *NodeSpecificConfig {
	if in == nil {
		return nil
	}
	out := new(NodeSpecificConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfig) DeepCopyInto(out *PluginConfig) {
	*out = *in
	in.DefaultConfig.DeepCopyInto(&out.DefaultConfig)
	if in.FileSystemSpecificConfigs != nil {
		in, out := &in.FileSystemSpecificConfigs, &out.FileSystemSpecificConfigs
		*out = make([]FileSystemSpecificConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfig.
func (in *PluginConfig) DeepCopy() *PluginConfig {
	if in == nil {
		return nil
	}
	out := new(PluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfigFromFile) DeepCopyInto(out *PluginConfigFromFile) {
	*out = *in
	in.PluginConfig.DeepCopyInto(&out.PluginConfig)
	if in.NodeSpecificConfigs != nil {
		in, out := &in.NodeSpecificConfigs, &out.NodeSpecificConfigs
		*out = make([]NodeSpecificConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfigFromFile.
func (in *PluginConfigFromFile) DeepCopy() *PluginConfigFromFile {
	if in == nil {
		return nil
	}
	out := new(PluginConfigFromFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSCertConfig) DeepCopyInto(out *TLSCertConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSCertConfig.
func (in *TLSCertConfig) DeepCopy() *TLSCertConfig {
	if in == nil {
		return nil
	}
	out := new(TLSCertConfig)
	in.DeepCopyInto(out)
	return out
}
